create table if not exists public.platform_template_version (
  template_version text primary key,
  template_scope text not null check (template_scope in ('foundation', 'module', 'patch')),
  template_status text not null check (template_status in ('draft', 'released', 'retired')),
  foundation_version text,
  description text,
  release_notes jsonb not null default '{}'::jsonb check (jsonb_typeof(release_notes) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  released_at timestamptz,
  created_by uuid
);

create table if not exists public.platform_template_table_registry (
  id bigint generated by default as identity primary key,
  template_version text not null references public.platform_template_version(template_version) on delete cascade,
  module_code text not null check (btrim(module_code) <> ''),
  source_schema_name text not null check (btrim(source_schema_name) <> ''),
  source_table_name text not null check (btrim(source_table_name) <> ''),
  target_table_name text not null check (btrim(target_table_name) <> ''),
  clone_order integer not null check (clone_order > 0),
  clone_enabled boolean not null default true,
  seed_mode text not null default 'none' check (seed_mode in ('none', 'copy_all_rows')),
  seed_filter jsonb not null default '{}'::jsonb check (jsonb_typeof(seed_filter) = 'object'),
  notes jsonb not null default '{}'::jsonb check (jsonb_typeof(notes) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by uuid,
  constraint platform_template_table_registry_source_key unique (template_version, source_schema_name, source_table_name),
  constraint platform_template_table_registry_target_key unique (template_version, target_table_name)
);

create table if not exists public.platform_schema_provisioning_run (
  run_id uuid primary key,
  tenant_id uuid not null references public.platform_tenant(tenant_id) on delete cascade,
  schema_name text not null check (btrim(schema_name) <> ''),
  operation_kind text not null check (operation_kind in ('schema_create', 'template_apply', 'schema_repair')),
  template_version text,
  run_status text not null check (run_status in ('running', 'succeeded', 'failed')),
  started_at timestamptz not null default timezone('utc', now()),
  finished_at timestamptz,
  actor_user_id uuid,
  source text not null check (btrim(source) <> ''),
  error_code text,
  error_message text,
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object')
);

create table if not exists public.platform_tenant_template_version (
  tenant_id uuid not null references public.platform_tenant(tenant_id) on delete cascade,
  template_version text not null references public.platform_template_version(template_version) on delete restrict,
  schema_name text not null check (btrim(schema_name) <> ''),
  apply_status text not null check (apply_status in ('pending', 'applied', 'failed')),
  applied_at timestamptz,
  run_id uuid references public.platform_schema_provisioning_run(run_id) on delete set null,
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (tenant_id, template_version)
);

create index if not exists idx_platform_template_version_status_scope
  on public.platform_template_version (template_status, template_scope);

create index if not exists idx_platform_template_table_registry_clone_lookup
  on public.platform_template_table_registry (template_version, clone_enabled, clone_order, id);

create index if not exists idx_platform_schema_provisioning_run_tenant_started
  on public.platform_schema_provisioning_run (tenant_id, started_at desc);

create index if not exists idx_platform_schema_provisioning_run_status_started
  on public.platform_schema_provisioning_run (run_status, started_at desc);

drop trigger if exists trg_platform_template_version_set_updated_at on public.platform_template_version;
create trigger trg_platform_template_version_set_updated_at
before update on public.platform_template_version
for each row
execute function public.platform_set_updated_at();

drop trigger if exists trg_platform_template_table_registry_set_updated_at on public.platform_template_table_registry;
create trigger trg_platform_template_table_registry_set_updated_at
before update on public.platform_template_table_registry
for each row
execute function public.platform_set_updated_at();

drop trigger if exists trg_platform_tenant_template_version_set_updated_at on public.platform_tenant_template_version;
create trigger trg_platform_tenant_template_version_set_updated_at
before update on public.platform_tenant_template_version
for each row
execute function public.platform_set_updated_at();

alter table public.platform_template_version enable row level security;
alter table public.platform_template_table_registry enable row level security;
alter table public.platform_schema_provisioning_run enable row level security;
alter table public.platform_tenant_template_version enable row level security;

create or replace function public.platform_build_schema_name(p_tenant_code text)
returns text
language plpgsql
immutable
as $function$
declare
  v_tenant_code text := public.platform_normalize_tenant_code(p_tenant_code);
  v_candidate text;
begin
  if v_tenant_code is null then
    return null;
  end if;

  v_candidate := 'tenant_' || v_tenant_code;

  if length(v_candidate) <= 63 then
    return v_candidate;
  end if;

  return 'tenant_' || left(v_tenant_code, 63 - length('tenant_') - 9) || '_' || left(md5(v_tenant_code), 8);
end;
$function$;

create or replace function public.platform_schema_exists(p_schema_name text)
returns boolean
language sql
stable
as $function$
  select exists (
    select 1
    from pg_namespace
    where nspname = p_schema_name
  );
$function$;

create or replace function public.platform_table_exists(p_schema_name text, p_table_name text)
returns boolean
language sql
stable
as $function$
  select exists (
    select 1
    from information_schema.tables
    where table_schema = p_schema_name
      and table_name = p_table_name
      and table_type = 'BASE TABLE'
  );
$function$;

create or replace function public.platform_start_schema_provisioning_run(
  p_tenant_id uuid,
  p_schema_name text,
  p_operation_kind text,
  p_template_version text,
  p_actor_user_id uuid,
  p_source text,
  p_details jsonb
)
returns uuid
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_run_id uuid := gen_random_uuid();
begin
  insert into public.platform_schema_provisioning_run (
    run_id,
    tenant_id,
    schema_name,
    operation_kind,
    template_version,
    run_status,
    actor_user_id,
    source,
    details
  )
  values (
    v_run_id,
    p_tenant_id,
    p_schema_name,
    p_operation_kind,
    p_template_version,
    'running',
    p_actor_user_id,
    p_source,
    coalesce(p_details, '{}'::jsonb)
  );

  return v_run_id;
end;
$function$;

create or replace function public.platform_finish_schema_provisioning_run(
  p_run_id uuid,
  p_run_status text,
  p_error_code text,
  p_error_message text,
  p_details jsonb
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  update public.platform_schema_provisioning_run
  set
    run_status = p_run_status,
    finished_at = timezone('utc', now()),
    error_code = p_error_code,
    error_message = p_error_message,
    details = details || coalesce(p_details, '{}'::jsonb)
  where run_id = p_run_id;
end;
$function$;

create or replace function public.platform_clone_registered_template_tables(
  p_tenant_id uuid,
  p_template_version text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_schema_name text;
  v_row record;
  v_created_tables integer := 0;
  v_existing_tables integer := 0;
  v_seeded_tables integer := 0;
  v_target_has_rows boolean;
  v_seeded_row_count bigint;
begin
  select schema_name
  into v_schema_name
  from public.platform_tenant
  where tenant_id = p_tenant_id;

  if v_schema_name is null then
    raise exception 'tenant % has no schema_name bound', p_tenant_id;
  end if;

  if not public.platform_schema_exists(v_schema_name) then
    raise exception 'schema % does not exist for tenant %', v_schema_name, p_tenant_id;
  end if;

  for v_row in
    select *
    from public.platform_template_table_registry
    where template_version = p_template_version
      and clone_enabled = true
    order by clone_order, id
  loop
    if not public.platform_table_exists(v_row.source_schema_name, v_row.source_table_name) then
      raise exception 'template source table %.% not found for template version %',
        v_row.source_schema_name, v_row.source_table_name, p_template_version;
    end if;

    if not public.platform_table_exists(v_schema_name, v_row.target_table_name) then
      execute format(
        'create table %I.%I (like %I.%I including all)',
        v_schema_name,
        v_row.target_table_name,
        v_row.source_schema_name,
        v_row.source_table_name
      );
      v_created_tables := v_created_tables + 1;
    else
      v_existing_tables := v_existing_tables + 1;
    end if;

    if v_row.seed_mode = 'copy_all_rows' then
      execute format(
        'select exists (select 1 from %I.%I limit 1)',
        v_schema_name,
        v_row.target_table_name
      )
      into v_target_has_rows;

      if not v_target_has_rows then
        execute format(
          'insert into %I.%I select * from %I.%I',
          v_schema_name,
          v_row.target_table_name,
          v_row.source_schema_name,
          v_row.source_table_name
        );

        get diagnostics v_seeded_row_count = row_count;

        if v_seeded_row_count > 0 then
          v_seeded_tables := v_seeded_tables + 1;
        end if;
      end if;
    end if;
  end loop;

  return jsonb_build_object(
    'schema_name', v_schema_name,
    'template_version', p_template_version,
    'created_tables', v_created_tables,
    'existing_tables', v_existing_tables,
    'seeded_tables', v_seeded_tables
  );
end;
$function$;

create or replace view public.platform_schema_provisioning_view as
select
  pt.tenant_id,
  pt.tenant_code,
  pt.schema_name,
  pt.display_name,
  pt.tenant_kind,
  pp.provisioning_status,
  pp.schema_provisioned,
  pp.foundation_version,
  pp.ready_for_routing,
  pp.latest_completed_step,
  pp.last_error_code,
  pp.last_error_message,
  pp.last_error_at,
  public.platform_schema_exists(pt.schema_name) as schema_exists,
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'template_version', ptv.template_version,
          'schema_name', ptv.schema_name,
          'apply_status', ptv.apply_status,
          'applied_at', ptv.applied_at
        )
        order by ptv.applied_at nulls last, ptv.template_version
      )
      from public.platform_tenant_template_version ptv
      where ptv.tenant_id = pt.tenant_id
    ),
    '[]'::jsonb
  ) as applied_versions,
  (
    select jsonb_build_object(
      'run_id', pspr.run_id,
      'operation_kind', pspr.operation_kind,
      'template_version', pspr.template_version,
      'run_status', pspr.run_status,
      'started_at', pspr.started_at,
      'finished_at', pspr.finished_at,
      'error_code', pspr.error_code,
      'error_message', pspr.error_message,
      'details', pspr.details
    )
    from public.platform_schema_provisioning_run pspr
    where pspr.tenant_id = pt.tenant_id
    order by pspr.started_at desc, pspr.run_id desc
    limit 1
  ) as latest_run
from public.platform_tenant pt
join public.platform_tenant_provisioning pp
  on pp.tenant_id = pt.tenant_id;;
