do $$
begin
  if not exists (
    select 1
    from pg_roles
    where rolname = 'simulator_agent'
  ) then
    create role simulator_agent login password 'SimBridge_20260323_A9mT4qR7pLc2Xn8K';
  else
    alter role simulator_agent login password 'SimBridge_20260323_A9mT4qR7pLc2Xn8K';
  end if;
end;
$$;

create table if not exists public.sim_fixture_execution_audit (
  id bigint generated by default as identity primary key,
  fixture_run_key text not null,
  phase text not null,
  suite_run_id uuid null,
  workflow_run_id uuid null,
  module text null,
  execution_mode text null,
  requested_by_role text null,
  requested_by_uid uuid null,
  sql_sha256 text not null,
  success boolean not null,
  result jsonb not null default '{}'::jsonb,
  error_message text null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint sim_fixture_execution_audit_phase_check check (phase in ('SEED', 'CLEANUP')),
  constraint sim_fixture_execution_audit_result_check check (jsonb_typeof(result) = 'object')
);

create index if not exists idx_sim_fixture_execution_audit_fixture_run_key
on public.sim_fixture_execution_audit (fixture_run_key, created_at desc);

create index if not exists idx_sim_fixture_execution_audit_suite_run_id
on public.sim_fixture_execution_audit (suite_run_id, created_at desc);

create or replace function public.sim_validate_persisted_fixture_sql(p_sql text)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_sql text;
  v_compact text;
begin
  v_sql := trim(coalesce(p_sql, ''));

  if v_sql = '' then
    raise exception 'Fixture SQL is required';
  end if;

  if length(v_sql) > 50000 then
    raise exception 'Fixture SQL exceeds 50000 characters';
  end if;

  v_sql := regexp_replace(v_sql, ';+\s*$', '', 'g');
  v_compact := trim(regexp_replace(v_sql, '\s+', ' ', 'g'));

  if v_compact ~* '(^|[^a-z_])(create|alter|drop|grant|revoke|truncate|comment|copy|vacuum|analyze|refresh|reindex|cluster|listen|notify|unlisten|set\s+role|reset\s+role|security\s+definer|execute\s+immediate|do\s*\$\$)([^a-z_]|$)' then
    raise exception 'Forbidden SQL keyword detected in fixture statement';
  end if;

  if not (
    left(lower(v_compact), 5) = 'with '
    or left(lower(v_compact), 7) = 'select '
    or left(lower(v_compact), 7) = 'insert '
    or left(lower(v_compact), 7) = 'update '
    or left(lower(v_compact), 7) = 'delete '
  ) then
    raise exception 'Fixture SQL must start with WITH, SELECT, INSERT, UPDATE, or DELETE';
  end if;

  if v_compact !~* 'jsonb_build_object|to_jsonb' then
    raise exception 'Fixture SQL must return a JSONB payload';
  end if;

  if v_compact ~* ';\s*(with|select|insert|update|delete)\b' then
    raise exception 'Only a single SQL statement is allowed';
  end if;
end;
$function$;

create or replace function public.execute_simulator_persisted_fixture(
  p_fixture_run_key text,
  p_phase text,
  p_sql text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_phase text := upper(trim(coalesce(p_phase, '')));
  v_fixture_run_key text := trim(coalesce(p_fixture_run_key, ''));
  v_sql text := trim(coalesce(p_sql, ''));
  v_result jsonb := '{}'::jsonb;
  v_error text := null;
  v_jwt_role text := coalesce(auth.role(), current_setting('request.jwt.claim.role', true));
  v_current_role text := current_user;
  v_session_role text := session_user;
  v_uid uuid := auth.uid();
  v_sql_sha256 text;
  v_suite_run_id uuid := nullif(p_metadata->>'suite_run_id', '')::uuid;
  v_workflow_run_id uuid := nullif(p_metadata->>'workflow_run_id', '')::uuid;
  v_module text := nullif(trim(p_metadata->>'module'), '');
  v_execution_mode text := nullif(trim(p_metadata->>'execution_mode'), '');
begin
  if coalesce(v_jwt_role, '') <> 'service_role' and v_session_role <> 'simulator_agent' then
    raise exception 'Only service_role or trusted simulator_agent may execute persisted simulator fixture SQL';
  end if;

  if v_phase not in ('SEED', 'CLEANUP') then
    raise exception 'Invalid fixture phase: %', v_phase;
  end if;

  if v_fixture_run_key = '' then
    raise exception 'fixture_run_key is required';
  end if;

  if length(v_fixture_run_key) > 200 then
    raise exception 'fixture_run_key exceeds 200 characters';
  end if;

  perform public.sim_validate_persisted_fixture_sql(v_sql);

  if right(v_sql, 1) = ';' then
    v_sql := left(v_sql, length(v_sql) - 1);
  end if;

  v_sql_sha256 := encode(extensions.digest(v_sql, 'sha256'), 'hex');

  begin
    execute v_sql into v_result;

    if jsonb_typeof(v_result) is distinct from 'object' then
      raise exception 'Persisted fixture SQL must return one JSONB object';
    end if;

    insert into public.sim_fixture_execution_audit (
      fixture_run_key,
      phase,
      suite_run_id,
      workflow_run_id,
      module,
      execution_mode,
      requested_by_role,
      requested_by_uid,
      sql_sha256,
      success,
      result,
      error_message
    ) values (
      v_fixture_run_key,
      v_phase,
      v_suite_run_id,
      v_workflow_run_id,
      v_module,
      v_execution_mode,
      coalesce(v_jwt_role, v_session_role, v_current_role),
      v_uid,
      v_sql_sha256,
      true,
      coalesce(v_result, '{}'::jsonb),
      null
    );

    return v_result;
  exception when others then
    v_error := sqlerrm;

    insert into public.sim_fixture_execution_audit (
      fixture_run_key,
      phase,
      suite_run_id,
      workflow_run_id,
      module,
      execution_mode,
      requested_by_role,
      requested_by_uid,
      sql_sha256,
      success,
      result,
      error_message
    ) values (
      v_fixture_run_key,
      v_phase,
      v_suite_run_id,
      v_workflow_run_id,
      v_module,
      v_execution_mode,
      coalesce(v_jwt_role, v_session_role, v_current_role),
      v_uid,
      v_sql_sha256,
      false,
      '{}'::jsonb,
      v_error
    );

    return jsonb_build_object(
      'success', false,
      'phase', v_phase,
      'fixture_run_key', v_fixture_run_key,
      'error', v_error
    );
  end;
end;
$function$;

create or replace function public.execute_simulator_persisted_seed(
  p_fixture_run_key text,
  p_sql text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language sql
security definer
set search_path to 'public', 'pg_temp'
as $function$
  select public.execute_simulator_persisted_fixture(
    p_fixture_run_key := p_fixture_run_key,
    p_phase := 'SEED',
    p_sql := p_sql,
    p_metadata := p_metadata
  );
$function$;

create or replace function public.execute_simulator_persisted_cleanup(
  p_fixture_run_key text,
  p_sql text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language sql
security definer
set search_path to 'public', 'pg_temp'
as $function$
  select public.execute_simulator_persisted_fixture(
    p_fixture_run_key := p_fixture_run_key,
    p_phase := 'CLEANUP',
    p_sql := p_sql,
    p_metadata := p_metadata
  );
$function$;

revoke all on public.sim_fixture_execution_audit from public, anon, authenticated;
revoke all on function public.sim_validate_persisted_fixture_sql(text) from public, anon, authenticated;
revoke all on function public.execute_simulator_persisted_fixture(text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.execute_simulator_persisted_seed(text, text, jsonb) from public, anon, authenticated;
revoke all on function public.execute_simulator_persisted_cleanup(text, text, jsonb) from public, anon, authenticated;

grant usage on schema public to simulator_agent;
grant execute on function public.sim_validate_persisted_fixture_sql(text) to service_role, simulator_agent;
grant execute on function public.execute_simulator_persisted_fixture(text, text, text, jsonb) to service_role, simulator_agent;
grant execute on function public.execute_simulator_persisted_seed(text, text, jsonb) to service_role, simulator_agent;
grant execute on function public.execute_simulator_persisted_cleanup(text, text, jsonb) to service_role, simulator_agent;;
