set search_path = public, pg_temp;

do $$
declare
  v_template_version text := public.platform_payroll_core_module_template_version();
  v_result jsonb;
begin
  v_result := public.platform_register_template_version(jsonb_build_object('template_version', v_template_version,'template_scope', 'module','module_code', 'PAYROLL_CORE','template_status', 'released','description', 'PAYROLL_CORE tenant-owned payroll engine baseline.','metadata', jsonb_build_object('slice', 'PAYROLL_CORE','module_code', 'PAYROLL_CORE')));
  if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE template version registration failed: %', v_result::text; end if;

  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payroll_area','target_table_name', 'wcm_payroll_area','clone_order', 100,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payroll area registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_component','target_table_name', 'wcm_component','clone_order', 110,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE component registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_component_dependency','target_table_name', 'wcm_component_dependency','clone_order', 120,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE component dependency registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_component_rule_template','target_table_name', 'wcm_component_rule_template','clone_order', 130,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE rule template registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_pay_structure','target_table_name', 'wcm_pay_structure','clone_order', 140,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE pay structure registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_pay_structure_component','target_table_name', 'wcm_pay_structure_component','clone_order', 150,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE structure component registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_pay_structure_version','target_table_name', 'wcm_pay_structure_version','clone_order', 160,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE structure version registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_employee_pay_structure_assignment','target_table_name', 'wcm_employee_pay_structure_assignment','clone_order', 170,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE assignment registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payroll_input_entry','target_table_name', 'wcm_payroll_input_entry','clone_order', 180,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE input registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payroll_batch','target_table_name', 'wcm_payroll_batch','clone_order', 190,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE batch registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_component_calculation_result','target_table_name', 'wcm_component_calculation_result','clone_order', 200,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE calculation result registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_preview_simulation','target_table_name', 'wcm_preview_simulation','clone_order', 210,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE preview registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payslip_run','target_table_name', 'wcm_payslip_run','clone_order', 220,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payslip run registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payslip_item','target_table_name', 'wcm_payslip_item','clone_order', 230,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payslip item registration failed: %', v_result::text; end if;
  v_result := public.platform_register_template_table(jsonb_build_object('template_version', v_template_version,'module_code', 'PAYROLL_CORE','source_schema_name', 'public','source_table_name', 'wcm_payslip_audit_event','target_table_name', 'wcm_payslip_audit_event','clone_order', 240,'notes', jsonb_build_object('slice', 'PAYROLL_CORE','kind', 'tenant_owned_table'))); if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payslip audit registration failed: %', v_result::text; end if;

  v_result := public.platform_register_async_worker(jsonb_build_object('worker_code', 'payroll_batch_worker','module_code', 'PAYROLL_CORE','dispatch_mode', 'db_inline_handler','handler_contract', 'platform_process_payroll_batch_job','is_active', true,'max_batch_size', 3,'default_lease_seconds', 600,'heartbeat_grace_seconds', 900,'retry_backoff_policy', jsonb_build_object('base_seconds', 90, 'multiplier', 2, 'max_seconds', 3600),'metadata', jsonb_build_object('slice', 'PAYROLL_CORE','notes', 'First clean payroll batch worker on shared F04 spine.')));
  if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payroll worker registration failed: %', v_result::text; end if;
  v_result := public.platform_register_async_worker(jsonb_build_object('worker_code', 'payslip_generation_worker','module_code', 'PAYROLL_CORE','dispatch_mode', 'db_inline_handler','handler_contract', 'platform_process_payslip_run_job','is_active', true,'max_batch_size', 10,'default_lease_seconds', 600,'heartbeat_grace_seconds', 900,'retry_backoff_policy', jsonb_build_object('base_seconds', 120, 'multiplier', 2, 'max_seconds', 3600),'metadata', jsonb_build_object('slice', 'PAYROLL_CORE','notes', 'First clean payslip payload worker on shared F04 spine; binary artifact materialization remains a later hosted delivery step.')));
  if coalesce((v_result->>'success')::boolean, false) is not true then raise exception 'PAYROLL_CORE payslip worker registration failed: %', v_result::text; end if;
end;
$$;;
